name: dev

on:
  push:
    branches: [ main ]

jobs:
  staging-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Deploy to staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_REMOTE_HOST }}
          username: ${{ secrets.DEV_REMOTE_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            cd /var/www/html/test
            
            git status
            ls -la
